# coding: utf-8

"""
    AquaPi Swagger API

    REST API for the AquaPi  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_settings_api import ComponentSettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentSettingsApi(unittest.TestCase):
    """ComponentSettingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.component_settings_api.ComponentSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_component_settings(self):
        """Test case for post_component_settings

        Returns the current component settings  # noqa: E501
        """
        pass

    def test_put_component_settings(self):
        """Test case for put_component_settings

        Sets a new component settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
