# coding: utf-8

"""
    AquaPi Swagger API

    REST API for the AquaPi  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lamp import Lamp  # noqa: E501
from swagger_client.rest import ApiException


class TestLamp(unittest.TestCase):
    """Lamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLamp(self):
        """Test Lamp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lamp.Lamp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
