# coding: utf-8

# flake8: noqa

"""
    AquaPi Swagger API

    REST API for the AquaPi  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.component_settings_api import ComponentSettingsApi
from swagger_client.api.post_api import PostApi
from swagger_client.api.put_api import PutApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.component_settings import ComponentSettings
from swagger_client.models.feeder import Feeder
from swagger_client.models.lamp import Lamp
from swagger_client.models.light_sensor import LightSensor
from swagger_client.models.pump import Pump
from swagger_client.models.thermometer import Thermometer
from swagger_client.models.water_flow_sensor import WaterFlowSensor
from swagger_client.models.water_level_sensor import WaterLevelSensor
