# coding: utf-8

"""
    AquaPi Swagger API

    REST API for the AquaPi

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.component_settings_api import ComponentSettingsApi


class TestComponentSettingsApi(unittest.TestCase):
    """ ComponentSettingsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.component_settings_api.ComponentSettingsApi()

    def tearDown(self):
        pass

    def test_post_component_settings(self):
        """
        Test case for post_component_settings

        Returns the current component settings
        """
        pass

    def test_put_component_settings(self):
        """
        Test case for put_component_settings

        Sets a new component settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
