# coding: utf-8

"""
    AquaPi Swagger API

    REST API for the AquaPi

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.push_configuration_api import PushConfigurationApi


class TestPushConfigurationApi(unittest.TestCase):
    """ PushConfigurationApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.push_configuration_api.PushConfigurationApi()

    def tearDown(self):
        pass

    def test_post_messages(self):
        """
        Test case for post_messages

        Returns the current PushConfigurations
        """
        pass

    def test_post_push_configuration(self):
        """
        Test case for post_push_configuration

        Returns the current PushConfigurations
        """
        pass

    def test_put_push_configuration(self):
        """
        Test case for put_push_configuration

        Sets new PushConfigurations
        """
        pass


if __name__ == '__main__':
    unittest.main()
