# coding: utf-8

"""
    AquaPi Swagger API

    REST API for the AquaPi

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.fishes_api import FishesApi


class TestFishesApi(unittest.TestCase):
    """ FishesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.fishes_api.FishesApi()

    def tearDown(self):
        pass

    def test_post_fishes(self):
        """
        Test case for post_fishes

        Returns the fishes that are inside the aquarium
        """
        pass

    def test_put_fishes(self):
        """
        Test case for put_fishes

        Sets the fishes that are in the aquarium
        """
        pass


if __name__ == '__main__':
    unittest.main()
