# coding: utf-8

"""
    AquaPi Swagger API

    REST API for the AquaPi

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.post_api import PostApi


class TestPostApi(unittest.TestCase):
    """ PostApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.post_api.PostApi()

    def tearDown(self):
        pass

    def test_post_component_settings(self):
        """
        Test case for post_component_settings

        Returns the current component settings
        """
        pass

    def test_post_fishes(self):
        """
        Test case for post_fishes

        Returns the fishes that are inside the aquarium
        """
        pass

    def test_post_messages(self):
        """
        Test case for post_messages

        Returns the current PushConfigurations
        """
        pass

    def test_post_plants(self):
        """
        Test case for post_plants

        Returns the plants in the soil
        """
        pass

    def test_post_push_configuration(self):
        """
        Test case for post_push_configuration

        Returns the current PushConfigurations
        """
        pass


if __name__ == '__main__':
    unittest.main()
